language: python
python:
- '3.6'
if: (type = push AND branch = master) OR (type = pull_request AND NOT branch =~ /no-ci/)
env:
  global:
  - DJANGO_ENVIRONMENT=test
  - DJANGO_LOGLEVEL=debug
  - secure: Nhb1lUWRA3UShDyVTOKhlLFQs3Hs8djc9lgNZK0s+p2N9cIzQKrwaOxlzT3Fhy+jExvR2oo6HiBvM6H6xjbXjK4ddcPSvHr45EMX21pHWTK4w4kSGW/UfthtWQPIUTxhwf3FpobFE+JfqAMRUchuJytt42SkJKFJNE7Eq++vHfC5son6g+f3bDzsr7IM9LfVzbyI/kSohU2+sfEisT69Xf9ElHkg7rWsVdo+BSSHyFi1v97avi8hNO/pIAB+AGJsfsEk08Sieo0QNPZvww8vo2z6hz48h3xR910c9G6nR8exnCVvm9Xwi7MROzmUL6lQ1E0cLz9szHz1VRfRdRqcPekiHQc9QIXpH/HlCEKz/6uX5mRbTbbvHmqmsoXLlHMn/imc0Hels/YctG1juKtN8Y7N5XDB20GlfgMQjvGaxfZnfLUCqRdS4eP3YvzEjopJ5HLKEt26RNLbP/fjSHMV20/EkDKAZ5NTB/x7EuIvsTdr4AvLJqkUhHomuVzP/WOAoXLPSAcs7KvZqrM9/Nf6jquwOKidRW9hmXNnVfLv/qThB0m8Q5cigKG901VR4iYXAn/Goxc9qyHX4c8bGCkJfwe/9UDrqBz8RVDPNkojAaFgHUuv86WW8YpkohxPDJF9jBZJ1LOKzeNo512/2j7M1BsAECE4NP2kfpmFvOP3foQ=
  - secure: x/hSdWsTRTfI40udo5olZErLrnp/3Bg7PqEzw+tXiQAo2e7uFpuFVnVqkR6GwrUqJakJ+ta8MSvoIbCVsvK0WijgYc3tsMyGRSaApXIXaFcLbMe82wwzxvH5tkvVk8W6ZW+PtAxxEAl7pJPDAs1/6Cb+wt+TfMYtX3FW5JHoR2Lr8G9jzLTn8hUIRWTuasx0jIFhyD+sYl/VDxAcoGpmigZbvCbFyO8ILlpKpLsYz284Vptd3hwqbpBfEDNrxbvFfMX7KEua756W7hGpzwxRyShaljfohjOOYVlWlKOzPcJGBprTeqayMzWhNs1syA733K0DH/MSgJXFBhonRGWimVAEYZrlrafxG0IFobCqA/o55OnJ04X0GTdpfaXP6fHcH54UKFTBVOJ29IrtS8Y3wOkk+xhGeCXcO/kKV56cKFFDp3ohfe2qO6qinhV3dg/xEVLDjnLSdP9SXQd1mtfJckSQ+7nYWqV4v6oId1QAG+jbk221A+W42wTclFpWUchK55mZNUVHq7aXxWY2zLTF0HXNtbQp6iwbHI4z8wQg6HY6yUHuBRJP/WOwpEeYw9x8tcMCAlNYstTCm16eQ2SWp0FDMC4nxo0+8GRxhmwBKhyFCnj3x6y5WUGtoBSH+JGlkgdJfltCd1FZyfIwyZUOTPNdg7RMMVfka2tij9MG4fI=
install:
- pip install -r requirements.txt
before_script:
- python manage.py migrate
script:
- coverage run manage.py test
after_script:
- coveralls
