version: '3.7'

services:
  web:
    build: .
    command: gunicorn ProgImageService.wsgi:application --bind 0.0.0.0:8000
    environment: 
        - DJANGO_ENVIRONMENT=prod
        - DJANGO_LOGLEVEL=info
        - DATABASE=postgres
        - SQL_HOST=db
        - SQL_PORT=5432
    ports:
      - 8000:8000
    depends_on:
        - db

  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=progimage
    - POSTGRES_PASSWORD=progimage
    - POSTGRES_DB=progimage
  
volumes:
    postgres_data: